[build]
  command = "npm run build"
  publish = "dist"

# Uncomment and set if your app is in a subfolder:
# [build]
#   base = "frontend"
#   command = "npm --prefix frontend ci && npm --prefix frontend run build"
#   publish = "dist"
